# Generated by Django 6.0.3 on 2026-03-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_app', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
